# Generated by Django 4.0.3 on 2022-03-04 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loyalties', '0003_alter_promocode_description_and_more'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='Start date')),
                ('end_date', models.DateTimeField(verbose_name='End date')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('drop_off', models.ManyToManyField(related_name='rents_drop_off', to='locations.location', verbose_name='Drop off')),
                ('pick_up', models.ManyToManyField(related_name='rents_pick_up', to='locations.location', verbose_name='Pick up')),
                ('promo_code', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rent', to='loyalties.promocode', verbose_name='Promo code')),
            ],
            options={
                'verbose_name': 'Rent',
                'verbose_name_plural': 'Rents',
                'ordering': ('-created',),
            },
        ),
    ]
