# Generated by Django 4.0.3 on 2022-03-03 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loyalties', '0003_alter_promocode_description_and_more'),
        ('rents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='promo_code',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rent', to='loyalties.promocode', verbose_name='Promo code'),
        ),
    ]
