# Generated by Django 4.0.3 on 2022-03-04 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rents', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rent',
            old_name='pick_up',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='rent',
            name='drop_off',
        ),
    ]
