# Generated by Django 4.0.3 on 2022-03-04 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loyalties', '0004_remove_promocode_promo_rule_delete_promorule'),
        ('rents', '0002_rename_pick_up_rent_location_remove_rent_drop_off'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rents', to='loyalties.promocode', verbose_name='Promo code'),
        ),
    ]
