# Generated by Django 4.0.3 on 2022-03-04 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('rents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='rent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='rents.rent', verbose_name='Rent'),
        ),
    ]
