# Generated by Django 4.0.3 on 2022-03-05 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_whatsapp',
            field=models.BooleanField(default=False, verbose_name='Is WhatsApp'),
        ),
    ]
