# Generated by Django 4.0.3 on 2022-03-16 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0001_initial'),
        ('rents', '0003_alter_rent_promo_code'),
        ('customers', '0004_alter_customer_is_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='transfer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_transfer', to='transfers.transfer', verbose_name='Transfer'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='rent',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_rent', to='rents.rent', verbose_name='Rent'),
        ),
    ]
