# Generated by Django 4.0.3 on 2022-03-16 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loyalties', '0004_remove_promocode_promo_rule_delete_promorule'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='Start date')),
                ('end_date', models.DateTimeField(verbose_name='End date')),
                ('pick_up', models.CharField(max_length=255, verbose_name='Pick up')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('drop_off', models.ManyToManyField(blank=True, null=True, related_name='transfers', to='locations.location', verbose_name='Drop off')),
                ('promo_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='loyalties.promocode', verbose_name='Promo code')),
            ],
            options={
                'verbose_name': 'Transfer',
                'verbose_name_plural': 'Transfers',
                'ordering': ('-created',),
            },
        ),
    ]
