# Generated by Django 4.0.3 on 2022-03-16 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('transfers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='drop_off',
            field=models.ManyToManyField(blank=True, related_name='transfers', to='locations.location', verbose_name='Drop off'),
        ),
    ]
