# Generated by Django 4.0.3 on 2022-03-24 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('transfers', '0002_alter_transfer_drop_off'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='drop_off',
        ),
        migrations.AddField(
            model_name='transfer',
            name='drop_off',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='locations.location', verbose_name='Drop off'),
            preserve_default=False,
        ),
    ]
