# Generated by Django 4.0.3 on 2022-03-03 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loyalties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_type', models.CharField(choices=[('Min hours', 'Min hours'), ('First hours', 'First hours'), ('Additional hours', 'Additional hours'), ('Fixed discount', 'Fixed discount')], max_length=63, verbose_name='Promo type')),
                ('required_hours', models.TimeField(verbose_name='Required hours')),
                ('bonus_hours', models.TimeField(verbose_name='Bonus hours')),
                ('discount_percentage', models.PositiveSmallIntegerField(verbose_name='Discount percentage')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'Promo rule',
                'verbose_name_plural': 'Promo rules',
                'ordering': ('-created',),
            },
        ),
        migrations.AddField(
            model_name='promocode',
            name='promo_rule',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='promo_codes', to='loyalties.promorule', verbose_name='Promo rule'),
            preserve_default=False,
        ),
    ]
